### ISSUE TITLE
OpenClipAdapter has different pretrained names

### ISSUE THREAD

**Issue by georgel2004** [lucidrains/classifier-free-guidance-pytorch#1]
Below change helps to provide any model name for open_clip at line number 36 in https://github.com/lucidrains/classifier-free-guidance-pytorch/blob/main/classifier_free_guidance_pytorch/open_clip.py

#pretrained = default(pretrained, DEFAULT_PRETRAINED_CLIP)
pretrained_list = dict(open_clip.list_pretrained())
pretrained = pretrained_list[name]

open_clip.list_pretrained() has model names like 'ViT-B-32' instead of 'ViT-B/32'

**Comment by lucidrains** [comment]
@georgel2004 oh yes, thanks for catching this!

are you using this repository for your research?
