### ISSUE TITLE
Wrong formula of Bytedance's version of classifier-free-guidance 

### ISSUE THREAD

**Issue by StarCycle** [lucidrains/classifier-free-guidance-pytorch#2]
https://github.com/lucidrains/classifier-free-guidance-pytorch/blob/b1ceb33a1c51ba99532b19d7bde9caf252fe75c0/classifier_free_guidance_pytorch/classifier_free_guidance_pytorch.py#L135-L144

I think the formula should be `rescaled_logits * rescale_phi + (1. - rescale_phi) * scaled_logits`, according to their paper

![image](https://github.com/lucidrains/classifier-free-guidance-pytorch/assets/33491471/2f64397a-41dc-46b5-bed9-55268bd893f7)

**Comment by lucidrains** [comment]
@StarCycle 🤦 yes, thank you

can you see if the latest commit resolves this?

**Comment by StarCycle** [comment]
Yes it does! Cheers!
